### ISSUE TITLE
Starter project does not work with build

### ISSUE THREAD

**Issue by ReactAcademyCa** [3nvi/gatsby-intl#1]
The starter project does not work with build.  (The language pages are generated, but the redirection pages are not. So you can access "site.com/en", but you can't access "site.com/" and then be redirected to "site.com/en".)

Although the project works fine with "npm run start" or "gatsby develop". Not sure why that is. 

Steps to reproduce the problem:

```
git clone https://github.com/3nvi/gatsby-intl intl-site
cd intl-site/packages/gatsby-starter-intl
npm install
gatsby clean
gatsby build
gatsby serve 
chrome http://localhost:9000
```

**Comment by 3nvi** [comment]
Hey there,

this behavior is intended, since redirects are not handled the same way in development & production. Specifically, during development, redirects are performed via Javascript, while during production, they are performed by the server receiving the request.

If you are wondering why we need server-side redirects and not just browser ones for production, it’s because we don’t want to rely on custom Javascript code to perform it for us. Users may disable scripting or have poor internet connections, which can lead to a late redirects. In addition, we can’t set a status code for a redirect, thus search engines won’t be able to index this action correctly. Relying on JS for development purposes is fine, but for production it’s a no-no.

The default behavior is to **omit** the creation of what you refer to as "redirection pages" when building for production since they are not truly needed, but include them during development. This is controlled through the `deleteOriginalPages` configuration key (you can read more options [here](https://github.com/3nvi/gatsby-intl/tree/master/packages/gatsby-plugin-intl#configuration).

So the question that still lies is "how is the redirect performed in production then"? Well that's up to the server. The starter includes `gatsby-plugin-netlify` which automatically creates a `_redirects` file, containing the redirects that Netlify should perform. As stated in the starter's description, this starter expects to use Netlify for deployment (which will handle redirects :)). Good news is that you can swap that for S3 if you want to. Simply replace `gatsby-plugin-netlify` with `gatsby-plugin-s3` and it will create the proper redirects for a deployment through S3.

Generally, the packages under this repo create the "redirect rules", but it's up to the deployment service (Netlify, Surge, S3, etc.) so parse those "rules" and create proper redirects. Gatsby itself [mentions that in their docs](https://www.gatsbyjs.org/docs/actions/#createRedirect). Specifically:

>Server redirects don’t work out of the box. You must have a plugin setup to integrate the redirect data with your hosting technology e.g. the Netlify plugin, or the Amazon S3 plugin. 

Thus, when running `gatsby serve` the server that serves your files found under `/public` has **no idea** of the redirects, unless you help him understand. If you deploy it though to Netlify, you'll see the redirects kicking in

**Comment by 3nvi** [comment]
One thing that I think I could do to help with that, is enhance `gatsby-plugin-intl` to:

1. Not delete the originalPages by default (by setting `deleteOriginalPages: false` as the default setting)

2. Add `<meta http-equiv="refresh" content="0; URL='/{DEFAULT_LOCALE}/'" />`  meta attributes to the original pages, so that even when you run `gatsby serve`, you can get this redirect out of the box.

This is similar to what [`gatsby-plugin-meta-redirect`](https://github.com/nsresulta/gatsby-plugin-meta-redirect) is doing. This won't work for redirects that depend on the `Accept-Language` header though

**Comment by ReactAcademyCa** [comment]
_"If you are wondering why we need server-side redirects and not just browser ones for production, it’s because [...]   search engines won’t be able to index this action correctly. Relying on JS for development purposes is fine, but for production it’s a no-no."_

Ok, I get that.  But isn't that already provided by "gatsby-plugin-intl", which you already wrap?  If I look at the documentation, over here: https://www.gatsbyjs.org/packages/gatsby-plugin-intl/ ,
it clearly states at the top:  "Support automatic redirection based on the user’s preferred language in browser provided by browser-lang".

Oh!  I just realized that the "gatsby-plugin-intl" that you are using is different than the one that is provided by the common plugin.  I thought you were wrapping the original one since you are supporting the same options.  But my assumption was wrong, it's a complete rewrite.

**Comment by 3nvi** [comment]
Oh yeah!

Funnily enough, I spotted this project **after** I already created this package. Had I known about its presence earlier, I wouldn't have bothered to "open source" my own approach.

The package is really nice, but it relies on JS to do the redirects. That was an issue for me since SEO is badly hurt from this and you might be redirected super late (when the JS bundle arrives). Other than that, great package :)
