### ISSUE TITLE
Proposed change to redirect logic

### ISSUE THREAD

**Issue by balibebas** [3nvi/gatsby-intl#11]
Hi Anggelo. Me again. Sorry for opening so many issues. I want to make one more suggestion after surfing through your quite comprehensive and very useful [related blog post](https://itnext.io/techniques-approaches-for-multi-language-gatsby-apps-8ba13ff433c5).

When visiting a website with Internationalizaton it would be preferable for a default language to _not_ redirect URLs. This is as a UX thing and if you ever copied a Wikipedia link then chopped off the `en` subdomain before sharing it you know what I'm talking about. So basically what I'm proposing is that, if a default language is specified (e.g. Greek), the site would serve up Greek by default and not at the `/el/` path.

It's okay if the explicit route and duplicate pages exist so long as `rel=canonical` is used. Please note I'm relatively new to Gatsby so I'm not sure if there are any technical limitations of what I'm proposting here. But maybe you know?

**Comment by balibebas** [comment]
I'm popping this in here to get you more visibility since official i18n support for Gatsby is, well, lackluster. https://github.com/angeloocana/gatsby-plugin-i18n/issues/12#issuecomment-648104448

**Comment by 3nvi** [comment]
Hey @balibebas I'll make a note to investigate that  during the weekend, so expect a reply by then :)

**Comment by 3nvi** [comment]
You are  right @balibebas . The `deleteOriginalPages` option was present just for this reason, but I seee that a redirect is still created. This is certainly  a bug from the plugin's side.

In the latest version ( `v0.4.12` ) this shouldn't be an issue anymore. In short, when you specify `deleteOriginalPages: false`:

* a redirect won't be created (since a page now exists at the redirect path)
* the canonical URL will  change from `/en/about/` to just `/about/` (since the original page is not deleted in our case)

Let me know if the solution is good enough and whether the alternate/canonical/hrefLang metas are setup the way you would expect them to be

**Comment by balibebas** [comment]
Sounds good to me. 👍🏼👍🏼
