### ISSUE TITLE
Translation do not work with theme

### ISSUE THREAD

**Issue by benouaghremhamza** [3nvi/gatsby-intl#2]
i just installed the plugin (theme-intl) , added this configuration : 
`  {
      resolve: `@3nvi/gatsby-theme-intl`,
      options: {
        supportedLanguages: ['en', 'fr'],
        i18nextConfig: {
          resources: {"en": { "translation":{ "de" : {"greeting": 'hello'}}}}, "fr": { "translation":{ "de" : { "greeting": 'bonjour'}}}},
        },
      },`

and imported useTranslation in a component  to test and it seems like something missing as i  tried ` {t("de")} ` and ` {t("de.greeting")} ` and just get de.greeting , but when i delete the de object and add only greeting , it works , how to make it works as i want to make all my pages in one json

**Comment by 3nvi** [comment]
Hey! `t("de.greeting")` should work automatically.

The [starter](https://github.com/3nvi/gatsby-intl/tree/master/packages/gatsby-starter-intl) has an example just like that, meaning that it has [deeply nested translations](https://github.com/3nvi/gatsby-intl/blob/54dbf75d7c12bf0f41b683d0589138b91cd3d9b3/packages/gatsby-starter-intl/i18n.json#L8-L11), which get accessed [exactly the same way as you said](https://github.com/3nvi/gatsby-intl/blob/master/packages/gatsby-starter-intl/src/pages/index.js#L13). I just verified that the starter works as expected.

Can you try deploying it following the instructions in the [README](https://github.com/3nvi/gatsby-intl/tree/master/packages/gatsby-starter-intl#installation), change the translations to what you wish and let me know if it works? There could be a typo somewhere that I can't see right now or it could be some sort of a weird bug.

In any case, let me know!

**Comment by benouaghremhamza** [comment]
i can't use the starter because i'm integrating it in an existing project

**Comment by benouaghremhamza** [comment]
i'll check it out to see where the bug is, , can you also help me to configure the urls ?

**Comment by 3nvi** [comment]
I used this setup in my `gatsby-config.js`

```js
{
      resolve: `@3nvi/gatsby-theme-intl`,
      options: {
        supportedLanguages: ['en', 'fr'],
        i18nextConfig: {
          resources: {
            "en": {
              "translation": {
                "de": {
                  "greeting": 'hello'
                }
              }
            },
            "fr": {
              "translation": {
                "de": {
                  "greeting": 'bonjour'
                }
              }
            }
          },
        },
      },
    },
```

then called

```javascript
const IndexPage = () => {
  const { t } = useTranslation()
  return (
    <h1>{t("de.greeting")}</h1>
  )
}
```

and everything work as expected. Can you verify that you just didn't have a typo?


As for your other comment, If you mean i18n-related URLs, then they should be automatically configured for you. You just need  a [language picker component](https://github.com/3nvi/gatsby-intl/blob/54dbf75d7c12bf0f41b683d0589138b91cd3d9b3/packages/gatsby-starter-intl/src/components/header.js#L41-L55) to allow you to change languages. Eveything else would be handled automatically for you.

Take a note that in production server-side redirects will work if you deploy to gatsby-affiliated providers (like S3 or Netlify). Read [this comment](https://github.com/3nvi/gatsby-intl/issues/1#issuecomment-612601324) for more info.

**Comment by benouaghremhamza** [comment]
i reinstalled and rewritten the config and it showed hello , thank you , but it won't switch language to fr even if i specify lng : "fr" , do you have any suggestion ? and thank you very much one more time

**Comment by 3nvi** [comment]
We are in the gatsby world. This means that we have static websites where each different language means a different page **entirely**.

Thus if you want to switch languages, you **have to** change a URL (since if you just changed it using javascript, Google wouldn't be able to pick up the fact that you have multiple languages supported in your website).

Thus if you are on the english about page (found under `/en/about/`) and you want to "switch language to french", you just have to redirect to the french version (found under `/fr/about/`). At the end of the day, switching languages meaning "switching the language prefix in the URL"

In my previous comment I provided a simple, yet helpful, [example of a component that does just that](https://github.com/3nvi/gatsby-intl/blob/54dbf75d7c12bf0f41b683d0589138b91cd3d9b3/packages/gatsby-starter-intl/src/components/header.js#L41-L55). Specifically, it iterates over your supported languages and creates "links to your current page" for each supported language. This works like a "language picker" but it's essentially a list of `<a>` elements.

The output looks like that:

<img width="1333" alt="Screen Shot 2020-04-15 at 5 42 47 PM" src="https://user-images.githubusercontent.com/10436045/79350822-9dc83680-7f40-11ea-98da-2ce0839ef599.png">

Of course you can create those links yourself, in any way you want  :)

**Comment by benouaghremhamza** [comment]
thank you very much for help :) , you helped me a lot

**Comment by 3nvi** [comment]
Cheers! Thanks for trying out the project :)
